apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: $GITHUB_ORG
  username: unused
  password: $GITHUB_TOKEN
